file:
  upload-path: D:/upload/
#  upload-path: /tmp/upload/files/

server:
  port: 8800
  servlet:
    context-path: /

spring:
  application:
    name: jinghu-cad
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
      location: ${file.upload-path}
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, file:${file.upload-path}/

#日志文件输出路径
logging:
  file:
    path: ./log